//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.monitoring.prinfo.Ressource {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.monitoring.prinfo.Ressource.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to initialize archiv.db. Integrity check failed ähnelt.
        /// </summary>
        internal static string archiv_db_initialize_failed {
            get {
                return ResourceManager.GetString("archiv_db_initialize_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Archiv database (archiv.db) integrity check failed. Recreating database ähnelt.
        /// </summary>
        internal static string archiv_db_integrity_failed {
            get {
                return ResourceManager.GetString("archiv_db_integrity_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error loading the config file: {0} ähnelt.
        /// </summary>
        internal static string config_error_load {
            get {
                return ResourceManager.GetString("config_error_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error searching XML Tag: {0} ähnelt.
        /// </summary>
        internal static string config_error_location {
            get {
                return ResourceManager.GetString("config_error_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed saving config file: {0} ähnelt.
        /// </summary>
        internal static string config_error_save {
            get {
                return ResourceManager.GetString("config_error_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Directory: {0} does not exist ähnelt.
        /// </summary>
        internal static string directory_not_exist {
            get {
                return ResourceManager.GetString("directory_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File does not exist ähnelt.
        /// </summary>
        internal static string file_not_exists {
            get {
                return ResourceManager.GetString("file_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Host is not listening to SNMP-Port. Please ensure that the port is not blocked by a firewall (Maybe not a printer) ähnelt.
        /// </summary>
        internal static string host_not_listening {
            get {
                return ResourceManager.GetString("host_not_listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Couldn`t reach host ähnelt.
        /// </summary>
        internal static string host_not_reachable {
            get {
                return ResourceManager.GetString("host_not_reachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Device reachable ähnelt.
        /// </summary>
        internal static string host_reachable {
            get {
                return ResourceManager.GetString("host_reachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Manager is holding {0} printers ähnelt.
        /// </summary>
        internal static string manager_holds {
            get {
                return ResourceManager.GetString("manager_holds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hostname is missing or null ähnelt.
        /// </summary>
        internal static string no_hostname {
            get {
                return ResourceManager.GetString("no_hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PrinterList checking started. ähnelt.
        /// </summary>
        internal static string printer_check_start {
            get {
                return ResourceManager.GetString("printer_check_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to initialize printer.db. Integrity check failed ähnelt.
        /// </summary>
        internal static string printer_db_inizialize_failed {
            get {
                return ResourceManager.GetString("printer_db_inizialize_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PrinterList database (printer.db) integrity check failed. Recreating database ähnelt.
        /// </summary>
        internal static string printer_db_integrity_failed {
            get {
                return ResourceManager.GetString("printer_db_integrity_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PrinterList Update aborted (Exception: {0}) ähnelt.
        /// </summary>
        internal static string printer_update_aborted {
            get {
                return ResourceManager.GetString("printer_update_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating printer failed - the printer has no Id. Did you create the printer over the PrinterDatabase.CreatePrinter()-Factory? ähnelt.
        /// </summary>
        internal static string printer_update_failed_no_id {
            get {
                return ResourceManager.GetString("printer_update_failed_no_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating printer failed - a printer with this Id does not exist ähnelt.
        /// </summary>
        internal static string printer_update_failed_wrong_id {
            get {
                return ResourceManager.GetString("printer_update_failed_wrong_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn`t send SMTP message.  ähnelt.
        /// </summary>
        internal static string smtp_error {
            get {
                return ResourceManager.GetString("smtp_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: ErrorException at SNMP Request Supply Number  ähnelt.
        /// </summary>
        internal static string snmp_error {
            get {
                return ResourceManager.GetString("snmp_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: SNMP Timeout, the host may be overloaded or is not answering SNMP requests ähnelt.
        /// </summary>
        internal static string snmp_timeout {
            get {
                return ResourceManager.GetString("snmp_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Integrity check of the read supplies failed. Supplies don`t fit the earlier checked supplies.  ähnelt.
        /// </summary>
        internal static string supply_integrity_failed {
            get {
                return ResourceManager.GetString("supply_integrity_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: Supply: {1} Procentual Value: {2}%; Actual Fill Value: {3} Max Fill Value: {4} OID: {5} ähnelt.
        /// </summary>
        internal static string supply_state {
            get {
                return ResourceManager.GetString("supply_state", resourceCulture);
            }
        }
    }
}
